const images = {
    add: require('../assets/images/add.png'),
    app_icon: require('../assets/images/app_icon.png'),
    back: require('../assets/images/left-arrow.png'),
    camera_border: require('../assets/images/camera_border.png'),
    card: require('../assets/images/card.png'),
    close: require('../assets/images/close.png'),
    header_bg: require('../assets/images/bg.png'),
    help_center: require('../assets/images/call-centre.png'),
    history: require('../assets/images/history.png'),
    image2: require('../assets/images/image2.png'),
    loan: require('../assets/images/loan.png'),
    logout: require('../assets/images/logout.png'),
    merchant: require('../assets/images/store.png'),
    notification: require('../assets/images/notification.png'),
    password: require('../assets/images/password.png'),
    profile: require('../assets/images/profile.png'),
    rating_empty: require('../assets/images/rating-empty.png'),
    rating_filled: require('../assets/images/rating-filled.png'),
    rewards: require('../assets/images/rewards.png'),
    sample: require('../assets/images/sample.png'),
    scan_qr: require('../assets/images/qr.png'),
    terms: require('../assets/images/agreement.png'),
};

export {images};