const images = {
    add: require('../assets/images/add.png'),
    app_icon: require('../assets/images/app_icon.png'),
    back: require('../assets/images/left-arrow.png'),
    camera_border: require('../assets/images/camera_border.png'),
    card: require('../assets/images/card.png'),
    close: require('../assets/images/close.png'),
    header_bg: require('../assets/images/bg.png'),
    help_center: require('../assets/images/call-centre.png'),
    history: require('../assets/images/history.png'),
    image2: require('../assets/images/image2.png'),
    loan: require('../assets/images/loan.png'),
    logout: require('../assets/images/logout.png'),
    merchant: require('../assets/images/store.png'),
    notification: require('../assets/images/notification.png'),
    password: require('../assets/images/password.png'),
    profile: require('../assets/images/profile.png'),
    rating_empty: require('../assets/images/rating-empty.png'),
    rating_filled: require('../assets/images/rating-filled.png'),
    rewards: require('../assets/images/rewards.png'),
    sample: require('../assets/images/sample.png'),
    scan_qr: require('../assets/images/qr.png'),
    terms: require('../assets/images/agreement.png'),

    // light icons
    accessories_and_apparels_light: require('../assets/images/Accessories-&-Apparels-01.png'),
    beauty_and_wellness_light: require('../assets/images/Beauty-&-Wellness-26.png'),
    electronics_and_appliances_light: require('../assets/images/Electronics-&-Appliances-20.png'),
    fitness_and_sports_light: require('../assets/images/Fitness-&-Sports-19.png'),
    hotels_and_resorts_light: require('../assets/images/Hotels-&-Resorts-17.png'),
    medical_light: require('../assets/images/Medical-16.png'),
    paymaya_light: require('../assets/images/paymaya-93.png'),
    restaurants_and_bars_light: require('../assets/images/Restaurants-&-Bars-12.png'),
    services_light: require('../assets/images/Services-21.png'),
    things_to_do_light: require('../assets/images/Things-to-do-15.png'),
    travel_light: require('../assets/images/Travel-14.png'),

    // dark icons
    accessories_and_apparels_dark: require('../assets/images/Accessories-&-Apparels_hover_-01.png'),
    beauty_and_wellness_dark: require('../assets/images/Beauty-&-Wellness_hover_-26.png'),
    electronics_and_appliances_dark: require('../assets/images/Electronics-&-Appliances_hover-20.png'),
    fitness_and_sports_dark: require('../assets/images/Fitness-&-Sports_hover_-19.png'),
    hotels_and_resorts_dark: require('../assets/images/Hotels-&-Resorts_hover_-17.png'),
    medical_dark: require('../assets/images/Medical_hover_-16.png'),
    paymaya_dark: require('../assets/images/paymaya_d-95.png'),
    restaurants_and_bars_dark: require('../assets/images/Restaurants-&-Bars_hover_-12.png'),
    services_dark: require('../assets/images/Services_hover-21.png'),
    things_to_do_dark: require('../assets/images/Things-to-do_hover_-15.png'),
    travel_dark: require('../assets/images/Travel_hover_-14.png'),
};

export {images};